# Generated by Django 5.2.6 on 2025-11-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssDumpInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity', models.CharField(max_length=40)),
                ('altitude', models.CharField(max_length=30)),
                ('visibility', models.CharField(max_length=30)),
                ('longitude', models.FloatField(max_length=50)),
                ('latitude', models.FloatField(max_length=50)),
            ],
        ),
    ]
